from clasehumano import Humano
from clasesuperhumano import SuperHumano
from claseartificiales import Artificiales
from clasealiens import Aliens
##Pruebas
humano = Humano("Kaladin")
humano.getStatus()
humano.verInventario()
humano.verLiga()
humano.verPoderes()
humano.verHabilidades()
humano.verDebilidades()
humano.verPersonalidad()
print("\n")

superhumano = SuperHumano("Yuno")
superhumano.getStatus()
superhumano.verInventario()
superhumano.verPoderes()
superhumano.verHabilidades()
superhumano.verDebilidades()
superhumano.verPersonalidad()
print("\n")

artificiales = Artificiales('Innova')
artificiales.getStatus()
artificiales.verInventario()
artificiales.verPoderes()
artificiales.verHabilidades()
artificiales.verDebilidades()
artificiales.verPersonalidad()
print("\n")

aliens = Aliens('Yoyo')
aliens.getStatus()
aliens.verInventario()
aliens.verPoderes()
aliens.verHabilidades()
aliens.verDebilidades()
aliens.verPersonalidad()
print("\n")
humano.atacar(aliens)
superhumano.atacar(artificiales)
artificiales.atacar(humano)
aliens.atacar(superhumano)